export default {
  items: [
    {
      name: "Dashboard",
      //label: "Dashboard",
      value: "/dashboard",
      url: "/dashboard",
      icon: "fa fa-tachometer",
      permission: "Dashboard",
    },
    {
      name: "Contracts",
      //label: "Contracts",
      value: "Contracts",
      icon: "fa fa-compress",
      children: [
        {
          name: "Contracts",
          url: "/contracts",
          //label: "Contracts Management",
          value: "/contracts",
          permission: "Contracts View Access",
          icon: "fa fa-compress",
        },
        {
          name: "Service Providers",
          url: "/serviceproviders",
          //label: "Contracts Management",
          value: "/serviceproviders",
          permission: "Contract-ServiceProviders View Access",
          icon: "fa fa-building",
        },
        {
          name: "Contract Report",
          url: "/contract-report",
          //label: "Contract Report",
          value: "/contract-report",
          permission: "Contract-Report View Access",
          icon: "fa fa-list-alt",
        },
        {
          name: "Retention Register",
          url: "/retention-register",
          value: "/retention-register",
          permission: "Contract-Report View Access",
          icon: "fa fa-list-alt",
        },
      ],
    },

    {
      name: "Registrations",
      icon: "fa fa-users",
      //label: "Registrations",
      value: "Registrations",
      children: [
        {
          name: "Farmers",
          url: "/farmers-data",
          //label: "Farmers Management",
          value: "/farmers-data",
          permission: "Farmers View Access",
          icon: "fa fa-users",
        },
        {
          name: "Farmers Report",
          url: "/farmers-reporting",
          value: "/farmers-reporting",
          permission: "Farmers View Access",
          icon: "fa fa-users",
        },

        {
          name: "Interactions",
          url: "/interaction-data",
          //label: "Interactions Management",
          value: "/interaction-data",
          permission: "Interaction View Access",
          icon: "fa fa-envelope-o",
        },
      ],
    },

    {
      name: "Performance",
      url: "/performance",
      value: "/performance",
      permission: "Performance View Access",
      icon: "fa fa-signal",
      children: [
        {
          name: "Programmes Master",
          url: "/programmes",
          value: "/programmes",
          permission: "Programmes View Access",
          icon: "fa fa-table",
        },
        {
          name: "Indicator Titles",
          url: "/indicatortitles",
          value: "/indicatortitles",
          permission: "IndicatorTitles View Access",
          icon: "fa fa-italic",
        },
        {
          name: "Plan & Assign Indicators",
          url: "/indicators",
          value: "/indicators",
          permission: "Indicators View Access",
          icon: "fa fa-map-signs",
        },
        {
          name: "Performance Reporting",
          url: "/performance",
          value: "/performance",
          permission: "Performance View Access",
          icon: "fa fa-signal",
        },
        {
          name: "Performance Moderate",
          url: "/performance-moderate",
          value: "/performance-moderate",
          permission: "Performance Moderate Access",
          icon: "fa fa-list",
        },
      ],
    },
    {
      name: "User Admin",
      value: "User Admin",
      icon: "fa fa-lock",

      children: [
        {
          name: "Users",
          url: "/users",
          //label: "Users",
          value: "/users",
          permission: "Users View Access",
          icon: "fa fa-user-plus",
        },
        {
          name: "Roles",
          url: "/usergroups",
          //label: "Roles",
          value: "/usergroups",
          permission: "Roles View Access",
          icon: "fa fa-users",
        },
        {
          name: "Approval Setup",
          url: "/approvalsetup",
          //label: "Approval Setup",
          value: "/approvalsetup",
          permission: "ApprovalSetup View Access",
          icon: "fa fa-cogs",
        },
        // {
        //   name: "Bank Master",
        //   url: "/banks",
        //   //label: "Bank Master",
        //   value: "/banks",
        //   permission: "Bank View Access",
        //   icon: "fa fa-building",
        // },
        {
          name: "Config Master",
          url: "/cnds",
          //label: "Config Master",
          value: "/cnds",
          permission: "ConfigMaster View Access",
          icon: "fa fa-asterisk",
        },
        {
          name: "Audit Log",
          url: "/activity-logs",
          //label: "Audit Log",
          value: "activity-logs",
          permission: "ActivityList View Access",
          icon: "fa fa-list",
        },
      ],
    },
  ],
};
